export const purple = '#991fde'
export const pink = '#de1fc4'
export const red = '#de1f64'
export const darkBlue = '#391fde'
export const lightBlue = '#1f64de'
export const white = '#ffffff'
export const gray = '#d8d7de'
